# Event name
name: on_push

# When the event should run (on push for all branches)
on:
  push:
    branches:
      - "**" # This will run on all branches and must be quoted to be handled by yaml.

      # What jobs to execute
jobs:

  build_and_test:
    runs-on: ubuntu-latest
    env:
      RUNNER_OS: true
      HEADLESS_CHROME: true

    steps:
    #set a start time
      - name: Set start time
        run: echo "START_TIME=$(date +%s)" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Run tests with maven
        working-directory: 'webdriver_java'
        run: mvn test
      - name: Collect build data
        working-directory: 'webdriver_java'
        if: always()
        run: |
          echo "TOTAL_DURATION=$(expr $(date +%s) - ${START_TIME})"
          ./resources/test_result_script.sh
    #calculate total duration
      #make sure to run even if a previous step fails